# Site settings
title: Coding Chronicles
header-img: img/home-bg.png
email: aderiannaw@yahoo.com
copyright_name: Atsoamazed
description: > # this means to ignore newlines until "baseurl:"
  Journey to becoming a Full stack developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: atsoamazed
github_username:  Atsoamazed
learn_profile: Atsoamazed
email_username: aderiannaw@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
